# Generated by Django 3.2.9 on 2021-11-18 08:38

from django.db import migrations, models
import statistics_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Количество показов')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество кликов')),
                ('cost', models.FloatField(default=0, validators=[statistics_app.validators.positive_value_validation], verbose_name='Стоимость клика')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
